language: android
jdk: openjdk7
android:
    components:
        - build-tools-22.0.1
        - build-tools-21.1.2
        - build-tools-21.1.1
        - build-tools-19.1.0
        - android-22
        - android-21
        - android-19
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
    licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
script:
    - ./gradlew testDebug jacocoTestReport coveralls --info
